# Generated by Django 5.2.1 on 2025-05-27 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('enseignant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('etudiant_id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('dateNaiss', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('etudiant', 'Etudiant'), ('enseignant', 'Enseignant')], default='etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('matiere_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=30)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('nbre_credit', models.IntegerField()),
                ('enseignant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.enseignants')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_evaluation', models.CharField(choices=[('controle_continu', 'CC'), ('session_normale', 'SN')], default='controle_continu')),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('Matiere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.matieres')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('etudiant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.etudiants')),
                ('evaluation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.evaluation')),
            ],
        ),
        migrations.AddField(
            model_name='etudiants',
            name='utilisateur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.utilisateurs'),
        ),
        migrations.AddField(
            model_name='enseignants',
            name='utilisateur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.utilisateurs'),
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('poste', models.CharField(choices=[('directeur', 'Directeur'), ('chef_departement', 'Chef de departememt'), ('vice_directeur', 'Vice directeur'), ('concepteur', 'Concepteur')], default='concepteur')),
                ('utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentManagerApp.utilisateurs')),
            ],
        ),
    ]
