# Generated by Django 5.2.1 on 2025-06-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='utilisateur_id',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='utilisateur_id',
        ),
        migrations.RemoveField(
            model_name='enseignants',
            name='utilisateur_id',
        ),
        migrations.AddField(
            model_name='admins',
            name='password',
            field=models.CharField(default='Lamborkini.1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enseignants',
            name='password',
            field=models.CharField(default='Lamborkini.1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiants',
            name='password',
            field=models.CharField(default='Lamborkini.1', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Utilisateurs',
        ),
    ]
