# Generated by Django 5.2.1 on 2025-07-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0002_remove_admins_utilisateur_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Administrateur',
        ),
        migrations.RenameModel(
            old_name='Enseignants',
            new_name='Enseignant',
        ),
        migrations.RenameModel(
            old_name='Etudiants',
            new_name='Etudiant',
        ),
        migrations.RenameModel(
            old_name='Matieres',
            new_name='Matiere',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
