# Generated by Django 5.2.1 on 2025-07-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0003_rename_admins_administrateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='admin_id',
            new_name='administrateur_id',
        ),
    ]
