# Generated by Django 5.2.1 on 2025-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0004_rename_admin_id_administrateur_administrateur_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='administrateur',
            constraint=models.UniqueConstraint(fields=('nom', 'password'), name='Constraint_of_unicity_name_password_administrateur'),
        ),
        migrations.AddConstraint(
            model_name='enseignant',
            constraint=models.UniqueConstraint(fields=('nom', 'password'), name='Constraint_of_unicity_name_password_enseignant'),
        ),
        migrations.AddConstraint(
            model_name='etudiant',
            constraint=models.UniqueConstraint(fields=('nom', 'password'), name='Constraint_of_unicity_name_password_etudiant'),
        ),
    ]
