# Generated by Django 5.2.1 on 2025-07-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0005_administrateur_constraint_of_unicity_name_password_administrateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
