# Generated by Django 5.2.1 on 2025-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0007_alter_enseignant_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='m'),
        ),
    ]
