# Generated by Django 5.2.1 on 2025-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0008_enseignant_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='m'),
        ),
    ]
