# Generated by Django 5.2.1 on 2025-07-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0009_etudiant_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='note',
        ),
    ]
