# Generated by Django 5.2.1 on 2025-07-10 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0013_alter_evaluation_type_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
