# Generated by Django 5.2.1 on 2025-07-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0016_evaluation_constraint_of_unicity_matiere_type_evaluation_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=30),
        ),
    ]
