# Generated by Django 5.2.1 on 2025-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0017_alter_etudiant_nom_alter_etudiant_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_utilisateur', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('administrateur', 'Administrateur')], max_length=20)),
                ('utilisateur_id', models.PositiveIntegerField()),
                ('token_session', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
