# Generated by Django 5.2.1 on 2025-10-15 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0018_sessionutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionutilisateur',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 16, 47, 51, 537354, tzinfo=datetime.timezone.utc)),
        ),
    ]
