# Generated by Django 5.2.1 on 2025-10-15 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0019_alter_sessionutilisateur_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionutilisateur',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 17, 2, 54, 791721, tzinfo=datetime.timezone.utc)),
        ),
    ]
