# Generated by Django 5.2.1 on 2025-10-15 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0020_alter_sessionutilisateur_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionutilisateur',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 17, 22, 1, 986412, tzinfo=datetime.timezone.utc)),
        ),
    ]
