# Generated by Django 5.2.1 on 2025-10-15 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0023_alter_sessionutilisateur_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionutilisateur',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionutilisateur',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 18, 33, 27, 962908, tzinfo=datetime.timezone.utc)),
        ),
    ]
