# Generated by Django 5.2.1 on 2025-10-29 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0024_sessionutilisateur_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionutilisateur',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 18, 6, 12, 479490, tzinfo=datetime.timezone.utc)),
        ),
    ]
