# Generated by Django 5.2.1 on 2025-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagerApp', '0025_alter_sessionutilisateur_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionutilisateur',
            name='date_expiration',
            field=models.DateTimeField(),
        ),
    ]
